name: google_places_autocomplete
description: Seamlessly integrate Google Places API into your Flutter app with this package. Get location autocomplete, detailed place info, and flexible UI implementation.

version: 2.0.0
homepage: https://github.com/Cuboid-Inc/google_places_autocomplete
repository: https://github.com/Cuboid-Inc/google_places_autocomplete

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:

flutter:
  plugin:
    platforms:
      android:
        package: com.cuboid.google_places_autocomplete
        pluginClass: GooglePlacesAutocompletePlugin
      ios:
        pluginClass: GooglePlacesAutocompletePlugin

topics:
  - network
  - http
  - google-places
  - flexible-ui
  - map
